- name: Add nodes to CouchDB cluster
  ansible.builtin.uri:
    url: http://{{ masternode }}:5984/_cluster_setup
    method: POST
    user: "{{ user }}"
    password: "{{ pass }}"
    force_basic_auth: yes
    status_code: 200, 201
    body_format: json
    body: "{\"action\": \"enable_cluster\", \"bind_address\": \"0.0.0.0\", \"username\":\"{{ user }}\", \"password\": \"{{ pass }}\", \"port\": \"5984\", \"remote_node\": \"{{ item }}\", \"node_count\": \"3\",\"remote_current_user\": \"{{ user }}\", \"remote_current_password\":\"{{ pass }}\"}"
    headers:
      Content-Type: "application/json" 
  loop: "{{ groups['CouchDB'] }}"

- name: Join nodes to CouchDB cluster
  ansible.builtin.uri:
    url: http://{{ masternode }}:5984/_cluster_setup
    method: POST
    user: "{{ user }}"
    password: "{{ pass }}"
    force_basic_auth: yes
    status_code: 200, 201
    body_format: json
    body: "{\"action\":\"add_node\",\"host\":\"{{ item }}\",\"port\":\"5984\",\"username\":\"{{ user }}\",\"password\":\"{{ pass }}\"}"
    headers:
      Content-Type: "application/json"  
  loop: "{{ groups['CouchDB'] }}"

- name: Finish cluster setup
  ansible.builtin.uri:
    url: http://{{ masternode }}:5984/_cluster_setup
    method: POST
    user: "{{ user }}"
    password: "{{ pass }}"
    force_basic_auth: yes
    status_code: 200, 201
    body_format: json
    body: "{\"action\":\"finish_cluster\"}"    
    headers:
      Content-Type: "application/json"
  run_once: true