# Installing packages/dependencies on host
- name: Install pip
  become: yes
  ansible.builtin.apt:
    # add in python3 application into list if needed
    name: ['python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Update pip
  become: yes
  ansible.builtin.pip:
    name: ['pip']
    state: latest

- name: Install dependencies
  become: yes
  tags: always
  ansible.builtin.apt:
    # add dependencies in the following list if more are needed 
    name: [
        "apt-transport-https",
        "build-essential",
        "ca-certificates",
        "curl",
        "git",
        "gnupg",
        "gnupg-agent",
        "lsb-release",
        "python3-dev",
        "python3-pip",
        "python3-setuptools",
        "snapd",
        "software-properties-common",
        "unzip",
        "vim",
      ]
    state: latest
    update_cache: yes
    install_recommends: no

  
