# Common Varaibles during instance creation 
availability_zone: melbourne-qh2-uom
instance_image: bbaf16f8-2484-48d7-b455-42209cc4b8d2 #NeCTAR Ubuntu 22.04 LTS (Jammy) amd64
instance_flavor: uom.mse.1c4g
instance_network: qh2-uom-internal
instance_keyname: ass2

# Volumes for each instances 
volumes:
  - vol_name: vol-for-instance1 
    vol_size: 60

  - vol_name: vol-for-intance2
    vol_size: 60

  - vol_name: vol-for-instance3
    vol_size: 60

  - vol_name: vol-for-instance4
    vol_size: 60

# Security Groups 
security_groups:
  - name: sec_ssh
    description: "security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: sec_http
    description: "security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb_sec_group1 
    description: "first security group for couchdb"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
  - name: couchdb_sec_group2 
    description: "second security group for couchdb"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
  - name: couchdb_sec_group3 
    description: "third security group for couchdb"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200


# Instances 
instances: 
  - name: intance1
    securitygroups: ['sec_ssh', 'couchdb_sec_group1', 'couchdb_sec_group2', 'couchdb_sec_group3']
    volumes: vol-for-instance1

  - name: intance2
    securitygroups: ['sec_ssh', 'couchdb_sec_group1', 'couchdb_sec_group2', 'couchdb_sec_group3']
    volumes: vol-for-instance2

  - name: intance3
    securitygroups: ['sec_ssh', 'couchdb_sec_group1', 'couchdb_sec_group2', 'couchdb_sec_group3']
    volumes: vol-for-instance3

  - name: intance4
    securitygroups: ['sec_ssh', 'sec_http']
    volumes: vol-for-instance4