# Common vars
availability_zone: melbourne-qh2-uom
instance_image: bbaf16f8-2484-48d7-b455-42209cc4b8d2
instance_key_name: ass2
instance_flavor: uom.mse.1c4g

# Volume
volumes:
  - vol_name: vol-for-instance1
    vol_size: 60
  - vol_name: vol-for-instance2
    vol_size: 60
  - vol_name: vol-for-instance3
    vol_size: 60
  - vol_name: vol-for-instance4
    vol_size: 60

# Security group
security_groups:
  - name: sec_ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: sec_http
    description: "Security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb_sec_group1 
    description: "first security group for couchdb"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb_sec_group2 
    description: "second security group for couchdb"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb_sec_group3 
    description: "third security group for couchdb"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: instance1
    securitygroups: ['sec_ssh', 'couchdb_sec_group1', 'couchdb_sec_group2', 'couchdb_sec_group3']
    volume: vol-for-instance1
  - name: instance2
    securitygroups: ['sec_ssh', 'couchdb_sec_group1', 'couchdb_sec_group2', 'couchdb_sec_group3']
    volume: vol-for-instance2
  - name: instance3
    securitygroups: ['sec_ssh', 'couchdb_sec_group1', 'couchdb_sec_group2', 'couchdb_sec_group3']
    volume: vol-for-instance3
  - name: instance4
    securitygroups: ['sec_ssh', 'sec_http']
    volume: vol-for-instance4
