#docker compose to activate Flask WEB APP 
- name: Operate Docker Compose 
  become: true
  docker_compose: 
    # project_src refers to the path on the remote host, not the controlling machine.
    # not too sure the direcrtory
    project_src: 
    pull: false
    build: true
    recreate: always 
    # Remove containers for services not defined in the Compose file.
    remove_orphans: false
    state: present 