# Installing dependencies | add any dependencies here with the latest state 
- name: Install pip
  become: yes
  ansible.builtin.apt:
    # add in python3 application into list if needed
    name: ['python3-dev', 'python3-setuptools', 'python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Update pip
  become: yes
  ansible.builtin.pip:
    name: ['pip', 'openstacksdk']
    state: latest