# Referred to the code provided on AlwynPan's Github 

- name: Install dependencies
  become: true
  tags: 'volumes'
  ansible.builtin.apt:
    name: ["xfsprogs"]
    state: latest
    install_recommends: false
    update_cache: true

- name: Make file system
  become: true
  tags: 'volumes' 
  community.general.filesystem:
    fstype: xfs
    dev: "{{ item.device }}"
  when: item.device is defined
  with_items:
    - "{{ volumes }}"

- name: Checking folders
  become: true
  tags: 'volumes'
  ansible.builtin.stat:
    path: "{{ item.mountpoint }}"
  register: directory_stats
  with_items:
    - "{{ volumes }}"

- name: Create directory
  become: true
  tags: 'volumes'
  ansible.builtin.file:
    path: "{{ item.item.mountpoint }}"
    recurse: true
    state: directory
  when: item.stat.exists == false
  with_items:
    - "{{ directory_stats.results }}"

- name: Mount device
  become: true
  tags: 'volumes'
  ansible.posix.mount:
    path: "{{ item.mountpoint }}"
    src: "{{ item.device }}"
    fstype: xfs
    state: mounted
  when: item.device is defined
  with_items:
    - "{{ volumes }}"