# Remove couchDB if one exist in the container
- name: Remove existing CouchDB container 
  become: true
  docker_container:
    name: couchdb
    state: absent

# Create new container with CouchDB
- name: Start new couchDB container
  become: true
  docker_container:
    name: "{{ couchdb_container_name}}"
    image: "{{ couchdb_image }}"
    state: started
    recreate: true
    ports:
      - "5984:5984"
      - "4369:4369"
      - "9100-9200:9100-9200"
    env:
      COUCHDB_USER: "{{ admin }}"
      COUCHDB_PASSWORD: "{{ admin }}"
      NODENAME: "{{ ansible_host }}"
      COUCHDB_SECRET: "{{ couchdb_cookie }}"