- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true

  roles:
    - role: common
    - role: createInstances
    - role: createVolumes
    - role: createSecurityGrps
    - role: images