# Setting up CouchDB
- hosts: Masternode
  vars_files:
    - host_vars/couchdb.yaml
  gather_facts: true
  roles:
    - role: couchDB_setup

- hosts: WorkerNodes
  vars_files:
    - host_vars/couchdb.yaml
  gather_facts: true
  roles:
    - role: installcouchDB